### PR TITLE
Form validation

### LINKED ISSUE #97: AaD, I would like better alerts and notifications for users when things go wrong so it's clear what is happening.
When things like "sign up", etc get failed API requests, the only way for the user to know is to open the console because there is no other notification.

related to talent-path-pipeline/server#5

### PR DESCRIPTION
**Pull request by rsanchez-dv**
Resolves #97 

Added proper form validations for login and signup.
* Shows validation errors once login/signup button is clicked
* Displays errors from the backend

### CODE REVIEW

File: src/components/registration/LogIn.js [hunk 1]
```diff
@@ -12,11 +12,21 @@ class LogIn extends Component {
     this.state = {
       email: '',
       password: '',
+      errors: {
+        email: false,
+        password: false,
+      },
+      ValidationErrorMessages: {
```
Comment (samsaksfithian) [inline src/components/registration/LogIn.js]: These are constant/set beforehand, so don't need to be in state. They can just be a constant object outside of state. Also, please use either the caps case naming convention because it's some constant info, or use snake case because it's a regular variable (and same for all of the contained keys).

```suggestion
      // outside of this.state
      this.validation_error_messages: {
```

File: src/components/registration/LogIn.js [hunk 2]
```diff
@@ -26,53 +36,91 @@ class LogIn extends Component {
...
+          this.setState({
+            HTTPErrorMessage: `Something went wrong on our side. Please try again at a later time.\n Error: ${error.response.data}`,
+          });
         }
       });
   };
 
-  render() {
+  handleEmailChange = evt => {
+    this.setState({ email: evt.target.value });
```
Comment (samsaksfithian) [inline src/components/registration/LogIn.js]: When changing/updating fields it should probably reset if there are errors, since they are now changing the data and it hasn't been checked with the new data.

```suggestion
    this.setState(prevState => ({ 
      email: evt.target.value, 
      errors: { ...prevState.errors, email: false }, 
      HTTPErrorMessage: '', 
    }));
```

File: src/components/registration/LogIn.js [hunk 3]
```diff
@@ -26,53 +36,91 @@ class LogIn extends Component {
...
+  };
+
+  handlePasswordChange = evt => {
+    this.setState({ password: evt.target.value });
```
Comment (samsaksfithian) [inline src/components/registration/LogIn.js]: Same as above

```suggestion
    this.setState(prevState => ({ 
      email: evt.target.value, 
      errors: { ...prevState.errors, password: false }, 
      HTTPErrorMessage: '', 
    }));
```

File: src/components/registration/LogIn.js [hunk 4]
```diff
@@ -12,11 +12,21 @@ class LogIn extends Component {
     this.state = {
       email: '',
       password: '',
```
Comment (samsaksfithian) [inline src/components/registration/LogIn.js]: Since you always use and pass these along together, it might make sense to store them wrapped together:

```
this.state = {
  data: {
    email: '',
    password: '';
  }

  ...
}

File: src/components/registration/LogIn.js [hunk 5]
```diff
@@ -26,53 +36,91 @@ class LogIn extends Component {
...
+    this.setState({ email: evt.target.value });
+  };
+
+  handlePasswordChange = evt => {
+    this.setState({ password: evt.target.value });
+  };
+
+  validateData = () => {
     const { email, password } = this.state;
+    let setErrors = { email: false, password: false };
```
Comment (samsaksfithian) [inline src/components/registration/LogIn.js]: You never reassign this object itself, just the contents, so this can just be constant.

```suggestion
    const setErrors = { email: false, password: false };
```

File: src/components/registration/LogIn.js [hunk 6]
```diff
@@ -26,53 +36,91 @@ class LogIn extends Component {
...
+    let atLeastOneFailed = false;
```
Comment (samsaksfithian) [inline src/components/registration/LogIn.js]: This is unnecessary, because you can just set the values in your `setErrors` object and then check the keys to see if any are true.

File: src/components/registration/LogIn.js [hunk 7]
```diff
@@ -26,53 +36,91 @@ class LogIn extends Component {
...
+      setErrors.email = true;
+      atLeastOneFailed = true;
+    }
+    // Validating password
+    if (password.length === 0 || password === undefined) {
+      setErrors.password = true;
+      atLeastOneFailed = true;
+    }
+    // Setting error flags in state
+    if (!atLeastOneFailed) {
```
Comment (samsaksfithian) [inline src/components/registration/LogIn.js]: Use array methods to just confirm that all values in your `setErrors` are false:

```suggestion
    if (Object.keys(setErrors).every(err_type => !setErrors[err_type])) {
```

File: src/components/registration/LogIn.js [hunk 8]
```diff
@@ -26,53 +36,91 @@ class LogIn extends Component {
...
+    // Validating Email
+    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
+      setErrors.email = true;
+      atLeastOneFailed = true;
+    }
+    // Validating password
+    if (password.length === 0 || password === undefined) {
+      setErrors.password = true;
+      atLeastOneFailed = true;
+    }
```
Comment (samsaksfithian) [inline src/components/registration/LogIn.js]: You can do all of this stuff in a simpler and more compact way right when you create your `setErrors` object if you don't need the `atLeastOneFailed` value (which you don't, because you can just check the values in `setErrors`, see below). Also, pls rename your variable because "setErrors" sounds like and is in the naming format of a function, not a variable.

```
const errors = {
  email: !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email),
  password: password.length === 0 || password === undefined,
};
```

File: src/components/registration/LogIn.js [hunk 9]
```diff
@@ -26,53 +36,91 @@ class LogIn extends Component {
...
+    // Setting error flags in state
+    if (!atLeastOneFailed) {
+      this.LogInHandler();
+    } else {
+      this.setState({ errors: setErrors });
```
Comment (samsaksfithian) [inline src/components/registration/LogIn.js]: Pls rename your error tracking variable

```suggestion
      this.setState({ errors });
```

File: src/components/registration/LogIn.js [hunk 10]
```diff
@@ -26,53 +36,91 @@ class LogIn extends Component {
...
-            type="email"
+            className={errors.email ? 'formError' : null}
+            type="text"
             value={email}
-            onChange={event => this.setState({ email: event.target.value })}
+            onChange={this.handleEmailChange}
+            placeholder=""
           />
+          {errors.email ? (
+            <p className="ErrorMessage">{this.state.ValidationErrorMessages.badEmail}</p>
```
Comment (samsaksfithian) [inline src/components/registration/LogIn.js]: Update this line once you take it out of state
```suggestion
            <p className="ErrorMessage">{this.validation_error_messages.bad_email}</p>
```

File: src/components/registration/LogIn.js [hunk 11]
```diff
@@ -26,53 +36,91 @@ class LogIn extends Component {
...
             type="password"
             value={password}
-            onChange={event => this.setState({ password: event.target.value })}
+            onChange={this.handlePasswordChange}
+            placeholder=""
           />
-          <button id="submit-button" type="button" onClick={this.LogInHandler}>
+          {errors.password ? (
+            <p className="ErrorMessage">
+              {this.state.ValidationErrorMessages.badPassword}
```
Comment (samsaksfithian) [inline src/components/registration/LogIn.js]: Update this line once you take it out of state
```suggestion
              {this.validation_error_messages.bad_password}
```

File: src/components/registration/SignUp.js [hunk 12]
```diff
@@ -5,45 +5,37 @@ import '../../css/registration/SignUp.scss';
...
   constructor(props) {
     super(props);
 
     this.state = {
-      // Form information
       email: '',
       password: '',
       confirmPassword: '',
       location: '',
       fullName: '',
```
Comment (samsaksfithian) [inline src/components/registration/SignUp.js]: Same as in Log In (but even moreso since there are more bits to be bundled together):

```
this.state = {
  data: {
    email: '',
    password: '',
    confirmPassword: '',
    location: '',
    fullName: '',
  }

  ...
}
```

File: src/components/registration/SignUp.js [hunk 13]
```diff
@@ -5,45 +5,37 @@ import '../../css/registration/SignUp.scss';
...
+        location: false,
+        fullName: false,
+      },
+      ValidationErrorMessages: {
+        badEmail: 'Must use a valid email',
+        badPassword: 'Must use a valid password with minimum of 8 characters',
+        badConfirmedPassword: 'Passwords do not match',
+        badFullName: 'Missing full name',
+        badLocation: 'Missing location',
       },
```
Comment (samsaksfithian) [inline src/components/registration/SignUp.js]: Again, same as Log In. These are constant and so can/should be moved outside of state. Also name should be switched to either constant (caps case) or variable (snake case) naming convention.

File: src/components/registration/SignUp.js [hunk 14]
```diff
@@ -53,37 +45,28 @@ class SignUp extends Component {
...
+          });
         }
       });
   };
 
   // Handles getting values
   handleEmailChange = evt => {
-    const email = evt.target.value;
-    this.setState({ email });
+    this.setState({ email: evt.target.value });
```
Comment (samsaksfithian) [inline src/components/registration/SignUp.js]: Same as Log In, all of these `handle______Change` functions should also reset the corresponding error and HTTP message

```suggestion
    this.setState(prevState => ({ 
      email: evt.target.value, 
      errors: { ...prevState.errors, email: false }, 
      HTTPErrorMessage: '', 
    }));
```

File: src/components/registration/SignUp.js [hunk 15]
```diff
@@ -102,127 +85,152 @@ class SignUp extends Component {
...
-  /**
-   * @description Controls the submit button
-   */
-  handleSubmit = evt => {
-    if (!this.canBeSubmitted()) {
-      evt.preventDefault();
-      return;
+  validateData = () => {
+    const { email, password, confirmPassword, location, fullName } = this.state;
+    let setErrors = {
```
Comment (samsaksfithian) [inline src/components/registration/SignUp.js]:
```suggestion
    const errors = {
```

File: src/components/registration/SignUp.js [hunk 16]
```diff
@@ -102,127 +85,152 @@ class SignUp extends Component {
...
+    // Validating Location
+    if (location.length === 0 || location === undefined) {
+      setErrors.location = true;
+      atLeastOneFailed = true;
+    }
+    // Setting error flags in state
+    if (!atLeastOneFailed) {
+      this.createUserHandler();
+    } else {
+      this.setState({ errors: setErrors });
```
Comment (samsaksfithian) [inline src/components/registration/SignUp.js]:
```suggestion
      this.setState({ errors });
```

File: src/components/registration/SignUp.js [hunk 17]
```diff
@@ -102,127 +85,152 @@ class SignUp extends Component {
...
+      setErrors.fullName = true;
+      atLeastOneFailed = true;
+    }
+    // Validating Location
+    if (location.length === 0 || location === undefined) {
+      setErrors.location = true;
+      atLeastOneFailed = true;
+    }
+    // Setting error flags in state
+    if (!atLeastOneFailed) {
```
Comment (samsaksfithian) [inline src/components/registration/SignUp.js]:
```suggestion
    if (Object.keys(errors).every(err_type => !errors[err_type])) {
```

File: src/components/registration/SignUp.js [hunk 18]
```diff
@@ -102,127 +85,152 @@ class SignUp extends Component {
...
+  validateData = () => {
+    const { email, password, confirmPassword, location, fullName } = this.state;
+    let setErrors = {
+      email: false,
+      password: false,
+      confirmPassword: false,
+      location: false,
+      fullName: false,
+    };
+    let atLeastOneFailed = false;
```
Comment (samsaksfithian) [inline src/components/registration/SignUp.js]:
```suggestion

```

File: src/components/registration/SignUp.js [hunk 19]
```diff
@@ -102,127 +85,152 @@ class SignUp extends Component {
...
+    // Validating Full Name
+    if (fullName.length === 0 || fullName === undefined) {
+      setErrors.fullName = true;
+      atLeastOneFailed = true;
+    }
+    // Validating Location
+    if (location.length === 0 || location === undefined) {
+      setErrors.location = true;
+      atLeastOneFailed = true;
+    }
```
Comment (samsaksfithian) [inline src/components/registration/SignUp.js]: You can check/validate the answers and set your object data all at once.
```
const errors = {
  email: !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email),
  password: password.length < 8 || password === undefined,
  confirm_password: confirm_password.length < 8 || password !== confirm_password,
  full_name: full_name.length <= 0 || full_name === undefined,
  location: location.length <= 0 || location === undefined,
};
```

**Review by samsaksfithian — DISMISSED** [review]
Some formatting, naming, and general code cleanup.

**Review by devmarantz — APPROVED** [review]
